name: Python application
on: 
    push: 
        branches: 
            - dev

jobs: 
    pepe:
        runs-on: self-hosted
        steps:
        - uses: actions/setup-python@v3
        - run: | 
            cd assignments
            cd exercise-2
            python main.py


